apiVersion: apexfintechsolutions.com/v1
kind: TransientRoleBinding
metadata:
  name: {{NAME}}
  namespace: {{NAMESPACE}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: User
    name: {{USER}}
validFrom: {{VALID_FROM}}
validUntil: {{VALID_UNTIL}}
